services:
  backend:
    build: ./backend
    container_name: backend
    restart: always
    env_file: 
      - ./backend/.env
    ports:
      - "5000:5000"
  
  frontend:
    build: 
      context: ./frontend
      args: 
        REACT_APP_API_URL: http://18.203.248.160:5000/todos
    container_name: frontend-v3
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend